django-projects/library/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeForm,
    PasswordResetView, PasswordResetConfirmView
)
from .import views

app_name = 'accounts'

urlpatterns = [
    path("register/", views.register, name='register'),
    # path("login/", views.login, name='login'),
    path("login/", LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path("logout/", LogoutView.as_view(template_name='accounts/login.html'), name='logout'),
    path("profile/", TemplateView.as_view(template_name='accounts/profile.html'), name='profile'),
    path("profile/edit/<pk>", views.ProfileEditView.as_view(),
         name='user_edit'),

    path("accounts/user/<pk>", views.OtherProfileView.as_view(), name='profile_view'),

    path("password/change/", PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url="/",
        form_class=PasswordChangeForm), name='password_change'),


    path("passoword/reset/", views.CustomPasswordReset.as_view(),
         name='password_reset'),

    path("password/reset/confirm/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm')
]

django-projects/library/library/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path("accounts/", include("accounts.urls", namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django-projects/library/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path("", views.BookListPageView.as_view(), name='home'),
    path("detail/<int:pk>/", views.BookDetailView.as_view(), name='book_detail'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='cat_list'),

    # CRUD
    path("add/", views.CreateBookView.as_view(), name='add'),
    path("update/<pk>", views.UpdateBookView.as_view(), name='update'),
    path("delete/<pk>", views.DeleteBookView.as_view(), name='delete')
]

django-projects/library/main/models.py
from django.db import models
from accounts.models import User

from ckeditor.fields import RichTextField
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return str(self.name)


class Book(models.Model):
    title = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True)
    author = models.ForeignKey(
        User, on_delete=models.PROTECT, blank=True, null=True)
    views = models.PositiveIntegerField(default=0, blank=True)
    poster = models.ImageField(upload_to='posters/')
    description = RichTextField()

    def __str__(self):
        return str(self.title)

django-projects/library/main/forms.py
from django.forms import ModelForm
from .models import Book

# Add new book form


class AddBookForm(ModelForm):

    class Meta:
        model = Book
        fields = ["title", "category", "poster"]
        exclude = ["views"]
        widgets = None

django-projects/library/main/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.
from .models import Book, Category


class BookListPageView(ListView):
    model = Book
    # template_name = 'index.html'


class BookDetailView(DetailView):
    model = Book


class CategoryListView(ListView):
    model = Category
    template_name = 'main/category_list.html'

    def get_queryset(self):
        if self.kwargs.get('slug'):
            category = self.model.objects.get(slug=self.kwargs.get('slug'))
            queryset = Book.objects.filter(category=category)
        return queryset

# CRUD Views


class CreateBookView(CreateView):
    # template_name = None
    # template_name_suffix = '_create'
    model = Book
    fields = ["title", "category", "poster", "description"]
    success_url = '/'

    def form_valid(self, form):
        user = self.request.user
        self.object = form.save(commit=False)
        self.object.author = user
        self.object.save()
        return super().form_valid(form)


class UpdateBookView(UpdateView):
    # book_update_form.html
    template_name = 'main/book_form.html'
    model = Book
    fields = ["title", "category", "poster"]
    success_url = '/'


class DeleteBookView(DeleteView):
    model = Book
    success_url = '/'

django-projects/library/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include '../assets/styles.html' %}
    <title>Document</title>

</head>

<body>
    <ul class="nav bg-dark py-2">
        {% for cat in categories %}
        <li class="nav-item px-5">
            <a href="{% url 'main:cat_list' cat.slug %}" class="nav-link fw-bold text-primary">{{cat.name}}</a>
        </li>
        {% endfor %}
        {% if request.user.is_authenticated %}
        <li class="nav-item px-5">
            <a href="{% url 'accounts:logout' %}" class="nav-link btn btn-outline-primary" title="Logout">
                Logout
                <i class="fa-solid fa-angle-left"></i>
            </a>
        </li>
        <li class="nav-item px-5">
            <a href="{% url 'accounts:profile' %}" class="nav-link btn btn-outline-primary" title="Profile">
                <i class="fa-solid fa-user"></i>
                {{request.user.username}}
            </a>
        </li>
        {% else %}
        <li class="nav-item px-5">
            <a href="{% url 'accounts:login' %}" class="nav-link btn btn-outline-primary" title="Login">
                Login
                <i class="fa-solid fa-angle-right"></i>
            </a>
        </li>
        {% endif %}

    </ul>
    {% if messages %}
    <div class="card my-5 p-3">
        <div class="messages w-25">
            {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }} p-3" {% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
                <a href="#" class="btn btn-outline-success float-end"
                    onclick="this.parentElement.parentElement.style.display = 'none'">
                    <i class=" fas fa-times"></i>
                </a>
        </div>
        {% endfor %}
    </div>
    </div>
    {% endif %}
    {% block content %}
    {% endblock %}

    <script src="{% static 'script.js' %}"></script>
</body>

</html>

django-projects/library/templates/main/book_confirm_delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include '../assets/styles.html' %}
    <title>Library </title>
</head>

<body>
    <div class="container">
        <h3>Delete Book {{object.title}}</h3>
        <br>
        <h2>Book object with title : {{object.title}} will be deleted ! <br>
            Are you sure ? </h2>
        {% load crispy_forms_tags %}
        <form action="" method="POST" class="w-50" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary my-3" type="submit">
                Yes
            </button>
        </form>
        <br><br>
        {% include '../assets/list.html' %}
    </div>
</body>

</html>

django-projects/library/templates/main/book_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% include '../assets/styles.html' %}
</head>

<body>
    <div class="container">
        <ul class="cats">
            {% for cat in categories %}
            <li>
                <a href="">{{cat.name}}</a>
            </li>
            {% endfor %}
        </ul>
        <ul class="cats">

            <li>
                <p>
                    <a href="{% url 'main:book_detail' book.id %}">
                        <img src="{{book.poster.url}}" width="100" alt="">
                    </a>
                </p>
                <h3>
                    <a href="{% url 'main:book_detail' book.id %}">
                        {{object.title}}
                    </a>
                </h3>
                <h5><a href="#">{{book.category}}</a></h5>
                <h5><a href="#">{{book.author}}</a></h5>
            </li>

        </ul>
    </div>
</body>

</html>

django-projects/library/templates/main/book_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include '../assets/styles.html' %}
    <title>Document</title>
</head>

<body>
    <div class="container">
        <h3>Book {% if request.path == '/add/' %}Add{% else %}Update{% endif %} Form</h3>
        <br>
        {% load crispy_forms_tags %}
        <form action="" method="POST" class="w-50" enctype="multipart/form-data">
            {% csrf_token %}

            {{form|crispy}}
            <button class="btn btn-primary my-3" type="submit">
                {% if request.path == '/add/' %}Add{% else %}Update{% endif %}
            </button>
        </form>
        <br><br>
        {% include '../assets/list.html' %}
    </div>
</body>

</html>

django-projects/library/templates/main/book_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="section container">
    <div class="row ">
        <div class="col-3">
            {% include '../assets/list.html' %}
        </div>
        <div class="col-9">
            <div class="row">
                {% for book in object_list %}
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="card" style="width: 18rem;">
                        <div class="card-image-top">
                            <img src="{{book.poster.url}}" class="card-img-top" alt="">
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h4>{{book.title}}</h4>
                                <h5><a href="#">{{book.category|upper}}</a></h5>
                                <h5><a href="{% url 'accounts:profile_view' book.author.id %}">{{book.author}}</a>
                                </h5>
                            </div>
                            <div class="d-flex flex-wrap gap-1">

                                <h5>
                                    <a href="{% url 'main:update' book.id %}" class="btn btn-outline-primary">
                                        <i class="fas fa-redo-alt"></i>
                                        Update
                                    </a>
                                </h5>
                                <h5>
                                    <a href="{% url 'main:delete' book.id %}" class="btn btn-outline-primary">
                                        <i class="fas fa-trash"></i>
                                        Delete
                                    </a>
                                </h5>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>


</div>
{% endblock %}

django-projects/library/templates/main/category_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            list-style: none;
            font-family: Arial, Helvetica, sans-serif;
        }

        .container {
            padding: 3%;
        }

        .cats {
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 10px;
        }

    </style>
</head>

<body>
    <div class="container">
        <ul class="cats">
            {% for cat in categories %}
            <li>
                <a href="{% url 'main:cat_list' cat.slug %}">{{cat.name}}</a>
            </li>
            {% endfor %}
        </ul>

        <ul>
            {% for book in object_list %}
            <li>
                <p>
                    <a href="{% url 'main:book_detail' book.id %}">
                        <img src="{{book.poster.url}}" width="100" alt="">
                    </a>
                </p>
                <h3>
                    <a href="{% url 'main:book_detail' book.id %}">
                        {{book.title}}
                    </a>
                </h3>
                <h5><a href="#">{{book.category}}</a></h5>
                <h5><a href="#">{{book.author}}</a></h5>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>