django-projects/db_managment/articles/urls.py
from django.urls import path 
from .import views 

app_name = 'articles'


urlpatterns = [
    path("", views.all_articles_view, name='post_list'),
    path('detail/<slug:article_slug>', views.post_detail, name='detail'),
    path("category/<slug:category_slug>/", views.category_list, name='category_list'),
    
    path('add/rating/', views.add_rating, name="add_rating"),
    path("delete/comment/<int:comment_id>", views.delete_comment, name='delete_comment'),
    
    path('add/', views.add_article, name='add_article')
]

django-projects/db_managment/db_managment/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth.views import LoginView

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('unicorn-app/', include('unicornapp.urls', namespace='unicornapp')),
    
    # Players App 
    path('', include('players.urls', namespace='players')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    
    
    path('admin/', admin.site.urls),
    
    
    
    path('main/', include('main_app.urls', namespace='main_app')),
    
    
    path('posts/', include('articles.urls', namespace='articles')),
    path('__debug__/', include('debug_toolbar.urls')),
    
    # AJAX - reactive Unicorn app 
    path("unicorn/", include("django_unicorn.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

django-projects/db_managment/main_app/urls.py
from django.urls import path
from .import views

app_name = 'main_app'

urlpatterns = [
    path('', views.testView, name='test'),
    path('search/', views.search, name='search'),
    path('add/course/', views.add_course_view, name="add_course")
]

django-projects/db_managment/players/urls.py
from django.urls import path
from .import views

app_name = 'players'

urlpatterns = [
    path('', views.PlayerListView.as_view(), name='players'),
    path('detail/<pk>', views.PlayerDetailView.as_view(), name='player_detail'),
    
    # filtering and sort 
    path('sort/by/club/<str:club_name>', views.SortByClub.as_view(), name='sort_by_club'),
    path('sort/by/position/<str:position>', views.SortByPositon.as_view(), name='sort_by_position'),
    path("filter-form/", views.PlayerFilterFormView.as_view(), name='player_filter_form'),
    path('sort_by_club_and_positon/', views.sort_by_club_and_positon, name='sort_by_club_and_positon')
    
]

django-projects/db_managment/templates/base.html
{% load static %}
{% load unicorn %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% unicorn_scripts %}
    <title>Document</title>
</head>
<header>
   
    <script>
        if ( window.history.replaceState ) {
            window.history.replaceState( null, null, window.location.href );
        }
    </script>
    <nav class="contianer">
        <ul class="nav px-5 py-3 ">
            <li class="nav-item">
                <a href="/" class="nav-link fw-bold">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'articles:post_list' %}" class="nav-link fw-bold">Posts</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'players:players' %}" class="nav-link fw-bold">Players</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'articles:add_article' %}" class="nav-link fw-bold">Add Post</a>
            </li>
        </ul>
    </nav>
</header>
<body>
{% block content %}
{% endblock %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

django-projects/db_managment/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <script>
        if ( window.history.replaceState ) {
            window.history.replaceState( null, null, window.location.href );
        }
    </script>
    {% if messages %}
        {% for message in messages %}
        <div class="messages">
            <h4>{{message}}</h4>
            <button onclick="this.parentElement.style.display= 'none'">X</button>
        </div>
        {% endfor %}
    {% endif %}
    <main>
        <br>
        <br>
        <div class="container">
            <h3 >Courses</h3>
            <h4>Add new course</h4>
            <form action="{% url 'main_app:add_course' %}" method="POST">
                {% csrf_token %}
                <p>
                    <input type="text" name="name" maxlength="100" placeholder="Name">
                    <input type="submit">
                </p>
            </form>
            <ul>
                {% for course in courses %}
                    <li>
                        {{course.name}}
                        <ol style="margin-left: 50px;">
                            {% for std in course.students.all %}
                            <li>{{std.name}}</li>
                            {% endfor %}
                        </ol>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <br>
        <br>
        <div class="container">
            <h3>Stacks</h3>
            <ul>
                {% for stack in stacks %}
                    {% if stack.stars > 5 %}
                    <li style="background-color: gold;">
                        {{stack.name}} <box-icon name='star'></box-icon>
                        {{stack.stars}}
                    </li>
                    {% else %}
                    <li>
                        <li>
                            {{stack.name}} <box-icon name='star'></box-icon>
                            {{stack.stars}}
                        </li>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <br>
        <br>
        <div class="container">
            <div class="my">
                <h3>Search objects...</h3>
                <form action="{% url 'main_app:search' %}" method="get">
                    <input type="text" name="q" placeholder="Search">
                    <input type="submit">
                </form>
            </div>
            <div class="my">
                {% if message %}
                <h3>{{message}}</h3>
                {% endif %}
                <ul>
                    {% for obj in object_list %}
                    <li>{{obj.name}} , {{obj.age}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </main>

{% endblock %}