django-projects/library/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeForm,
    PasswordResetView, PasswordResetConfirmView
)
from .import views

app_name = 'accounts'

urlpatterns = [
    path("register/", views.register, name='register'),
    # path("login/", views.login, name='login'),
    path("login/", LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path("logout/", LogoutView.as_view(template_name='accounts/login.html'), name='logout'),
    path("profile/", TemplateView.as_view(template_name='accounts/profile.html'), name='profile'),
    path("profile/edit/<pk>", views.ProfileEditView.as_view(),
         name='user_edit'),

    path("accounts/user/<pk>", views.OtherProfileView.as_view(), name='profile_view'),

    path("password/change/", PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url="/",
        form_class=PasswordChangeForm), name='password_change'),


    path("passoword/reset/", views.CustomPasswordReset.as_view(),
         name='password_reset'),

    path("password/reset/confirm/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm')
]

django-projects/library/library/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path("accounts/", include("accounts.urls", namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django-projects/library/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path("", views.BookListPageView.as_view(), name='home'),
    path("detail/<int:pk>/", views.BookDetailView.as_view(), name='book_detail'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='cat_list'),

    # CRUD
    path("add/", views.CreateBookView.as_view(), name='add'),
    path("update/<pk>", views.UpdateBookView.as_view(), name='update'),
    path("delete/<pk>", views.DeleteBookView.as_view(), name='delete')
]

django-projects/library/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    GENDERS = (
        ("Men", "men"),
        ("Women", "women")
    )

    age = models.PositiveIntegerField(default=0, blank=True)
    gender = models.CharField(choices=GENDERS, blank=True, max_length=30)
    bio = models.TextField(blank=True)
    photo = models.ImageField(upload_to=f'users/', blank=True)

    def get_user_fullname(self):
        name = ""
        if self.first_name and self.last_name:
            name = f"{self.first_name.title()} {self.last_name.title()}"
        else:
            name = "No user full name"
        return name

    def __str__(self):
        return str(self.username)

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

django-projects/library/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from django.core.exceptions import ValidationError


class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "email"]

        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            # "password": forms.PasswordInput(attrs={"class": "form-control"})
            # "last_name": forms.CharField(attrs={"class": "form-control"})
        }

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
        return password2

django-projects/library/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group

# password reset views
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin


from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.contrib import messages
# Create your views here.
from .models import User
from .forms import CreateUserForm


def register(request):
    form = CreateUserForm()

    if request.method == "POST":

        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            # add user to group
            gp = Group.objects.get(name="users")
            user.groups.add(gp.id)
            user.save()
            # login new user
            login(request, user)
            messages.add_message(request, messages.SUCCESS, "Well done !")
            return redirect("/")
        else:
            messages.add_message(request, messages.WARNING,
                                 "Something went wrong !")
    else:

        return render(request, "accounts/register.html", {"form": form})
    return render(request, "accounts/register.html", {"form": form})


class ProfileEditView(UpdateView):
    model = User
    fields = ["first_name", "last_name", "photo", "gender", "age", "bio"]
    success_url = "/accounts/profile"


class OtherProfileView(DetailView):
    model = User


class CustomPasswordReset(PasswordResetView, SuccessMessageMixin):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject.html'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users-home')

django-projects/library/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include '../assets/styles.html' %}
    {% block title %}
    <title>Accounts - Library</title>
    {% endblock %}
</head>

<body>
    <ul class="nav bg-dark py-2">
        {% for cat in categories %}
        <li class="nav-item px-5">
            <a href="{% url 'main:cat_list' cat.slug %}" class="nav-link fw-bold text-primary">{{cat.name}}</a>
        </li>
        {% endfor %}
        {% if request.user.is_authenticated %}
        <li class="nav-item px-5">
            <a href="{% url 'accounts:logout' %}" class="nav-link btn btn-outline-primary" title="Logout">
                Logout
                <i class="fa-solid fa-angle-left"></i>
            </a>
        </li>
        <li class="nav-item px-5">
            <a href="{% url 'accounts:profile' %}" class="nav-link btn btn-outline-primary" title="Profile">
                <i class="fa-solid fa-user"></i>
                {{request.user.username}}
            </a>
        </li>
        {% else %}
        <li class="nav-item px-5">
            <a href="{% url 'accounts:login' %}" class="nav-link btn btn-outline-primary" title="Login">
                Login
                <i class="fa-solid fa-angle-right"></i>
            </a>
        </li>
        {% endif %}

    </ul>
    {% if messages %}
    <div class="card my-5 p-3">
        <div class="messages w-25">
            {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }} p-3" {% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
                <a href="#" class="btn btn-outline-success float-end"
                    onclick="this.parentElement.parentElement.style.display = 'none'">
                    <i class="fas fa-times"></i>
                </a>
        </div>
        {% endfor %}
    </div>
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}

    <script src="{% static 'script.js' %}"></script>
</body>

</html>

django-projects/library/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="d-flex flex-wrap justify-content-center gap-2">
        {% if request.path == '/accounts/login/' %}
        <div class="mt-5 px-5 card border-none shadow-lg">
            <div class="text-center py-3">
                <h3 class="fw-bold">Login Form</h3>
            </div>
            <form action="" class="p-2" method="POST">
                {% csrf_token %}
                {{form}}
                <p class="mt-3">
                    <input type="submit" value="Login" class="btn btn-outline-success">
                </p>
                <p>
                    Forget your password ? <a href="{% url 'accounts:password_reset' %}">Reset my passowrd</a>
                </p>
                <p>
                    Don't have an account ? <a href="{% url 'accounts:register' %}">Register now</a>
                </p>

            </form>
        </div>
        {% else %}
        <div class="mt-5 px-5 card border-none shadow-lg">
            <br><br>
            <h4>Get back soon !</h4>
            <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">Go back</a>
        </div>
        {% endif %}
        <div class="image">
            <img class="img-fluid" width="400" src="{% static 'img/login.png' %}" alt="">
        </div>
    </div>
</div>
{% endblock %}

django-projects/library/templates/accounts/password_change.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<!-- title  -->
{% block title %}
<title>
    Password change -
    {% if request.user.first_name %}
    {{request.user.first_name}}
    {% else %}
    {{request.user.username}}
    {% endif %}
</title>
{% endblock title %}

<div class="container">
    <div class="d-flex flex-wrap justify-content-center gap-1">

        <div class="mt-5 px-5 card border-none shadow-lg">
            <div class="text-center py-3">
                <h3 class="fw-bold">Password Change Form</h3>
            </div>
            <form action="" class="w-100 p-2" method="POST">
                {% csrf_token %}

                {{form}}

                <p class="mt-3">
                    <input type="submit" value="Change password" class="btn btn-outline-success">
                </p>

            </form>
        </div>

        <div class="image">
            <img class="img-fluid" width="400" src="{% static 'img/login.png' %}" alt="">
        </div>
    </div>
</div>
{% endblock %}

django-projects/library/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="card-header justify-content-center">
                        <div id="error_div"></div>
                        <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                    </div>
                    {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <div id="form_errors">
                            {% for key, value in form.errors.items %}
                            <strong>{{ value }}</strong>
                            {% endfor %}
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email" class="form-control" autocomplete="email"
                                            maxlength="254" required id="id_email" placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="btn btn-outline-success">Submit
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url 'accounts:register' %}">Create A New Account</a><br><br>
                            <a href="{% url 'accounts:login' %}">Back To Login</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

django-projects/library/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}
{% block title %} Password Reset {% endblock title%}
{% block content %}
<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if validlink %}
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="card-header justify-content-center">
                        <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                    </div>
                    {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <div id="form_errors">
                            {% for key, value in form.errors.items %}
                            <strong>{{ value }}</strong>
                            {% endfor %}
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}

                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <label class="small mb-1" for="id_new_password1">New Password</label>
                                        <input type="password" name="new_password1" autocomplete="new-password"
                                            class="form-control" required id="id_new_password1"
                                            placeholder="Enter password" />
                                        <span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <label class="small mb-1" for="id_new_password2">New Password
                                            Confirmation</label>
                                        <input type="password" name="new_password2" autocomplete="new-password" required
                                            id="id_new_password2" class="form-control" placeholder="Confirm password" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset
                                            Password</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                {% else %}
                <div class="alert alert-warning">
                    The password reset link was invalid, possibly because it has already been used.
                    Please request a new password reset.
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

django-projects/library/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Chala Developer.
{% endautoescape %}

django-projects/library/templates/accounts/password_reset_subject.html
NoReverseMatch at /accounts/login/
Reverse for 'password_reset' not found. 'password_reset' is not a valid view function or pattern name.

django-projects/library/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<!-- title  -->
{% block title %}
<title>
    Profile -
    {% if request.user.first_name %}
    {{request.user.first_name}}
    {% else %}
    {{request.user.username}}
    {% endif %}
</title>
{% endblock title %}
<!-- end title  -->
<div class="container">
    <section>
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-4">

                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="{% if request.user.photo %} {{request.user.photo.url}} {% else %}https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp {% endif %}"
                                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
                            <h5 class="my-3">{{request.user.get_user_fullname}}</h5>
                            <p class="text-muted mb-1">{{request.user.username}}</p>
                            <p class="text-muted mb-4">Age : {{request.user.age}}</p>
                            <div class="d-flex justify-content-center mb-2">
                                <a href=""
                                    class="btn btn-primary">Edit</a>
                                <button type="button" class="btn btn-outline-primary ms-1">Message</button>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4 mb-lg-0">
                        <div class="card-body p-0">
                            <ul class="list-group list-group-flush rounded-3">
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fas fa-globe fa-lg text-warning"></i>
                                    <p class="mb-0">https://mdbootstrap.com</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                                    <p class="mb-0">mdbootstrap</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                                    <p class="mb-0">@mdbootstrap</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                                    <p class="mb-0">mdbootstrap</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                                    <p class="mb-0">mdbootstrap</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Full Name</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{request.user.get_user_fullname}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Email</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{request.user.email}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Gender</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{request.user.gender}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Bio</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">
                                        {{request.user.bio}}
                                    </p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col">
                                    <a href="{% url 'accounts:password_change' %}"
                                        class="btn btn-outline-primary">Change password</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                    </div>
                </div>
            </div>
        </div>
    </section>

</div>
{% endblock %}

django-projects/library/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="d-flex flex-wrap justify-content-center gap-2">

        <div class="mt-5 px-5 card border-none shadow-lg">
            <div class="text-center py-3">
                <h3 class="fw-bold">Register Form</h3>
            </div>
            <form action="{% url 'accounts:register' %}" class="p-2" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <p class="my-1">

                    <label for="id_{{field.name}}">{{field.name.title}}</label>
                    {{field}}
                </p>
                {% endfor %}
                <p class="mt-3">
                    <input type="submit" value="Login" class="btn btn-outline-success">
                </p>
                <p>
                    Don't have an account ? <a href="{% url 'accounts:register' %}">Register now</a>
                </p>
            </form>
        </div>

        <div class="image">
            <img class="img-fluid" width="400" src="{% static 'img/login.png' %}" alt="">
        </div>
    </div>
</div>
{% endblock %}

django-projects/library/templates/accounts/user_detail.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<!-- title  -->
{% block title %}
<title>
    Profile -
    {% if request.user.first_name %}
    {{request.user.first_name}}
    {% else %}
    {{request.user.username}}
    {% endif %}
</title>
{% endblock title %}
<!-- end title  -->
<div class="container">
    <section>
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-4">

                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="{% if user.photo %} {{user.photo.url}} {% else %}https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp {% endif %}"
                                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
                            <h5 class="my-3">{{user.get_user_fullname}}</h5>
                            <p class="text-muted mb-1">{{user.username}}</p>
                            <p class="text-muted mb-4">Age : {{user.age}}</p>
                            <div class="d-flex justify-content-center mb-2">

                                <button type="button" class="btn btn-outline-primary ms-1">Message</button>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4 mb-lg-0">
                        <div class="card-body p-0">
                            <ul class="list-group list-group-flush rounded-3">
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fas fa-globe fa-lg text-warning"></i>
                                    <p class="mb-0">https://mdbootstrap.com</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                                    <p class="mb-0">mdbootstrap</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                                    <p class="mb-0">@mdbootstrap</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                                    <p class="mb-0">mdbootstrap</p>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                                    <p class="mb-0">mdbootstrap</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Full Name</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{user.get_user_fullname}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Email</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{user.email}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Gender</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{user.gender}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Bio</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">
                                        {{user.bio}}
                                    </p>
                                </div>
                            </div>
                            <hr>

                        </div>
                    </div>
                    <div class="row">

                    </div>
                </div>
            </div>
        </div>
    </section>

</div>
{% endblock %}