django-projects/db_managment/db_managment/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth.views import LoginView

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('unicorn-app/', include('unicornapp.urls', namespace='unicornapp')),
    
    # Players App 
    path('', include('players.urls', namespace='players')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    
    
    path('admin/', admin.site.urls),
    
    
    
    path('main/', include('main_app.urls', namespace='main_app')),
    
    
    path('posts/', include('articles.urls', namespace='articles')),
    path('__debug__/', include('debug_toolbar.urls')),
    
    # AJAX - reactive Unicorn app 
    path("unicorn/", include("django_unicorn.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

django-projects/db_managment/players/urls.py
from django.urls import path
from .import views

app_name = 'players'

urlpatterns = [
    path('', views.PlayerListView.as_view(), name='players'),
    path('detail/<pk>', views.PlayerDetailView.as_view(), name='player_detail'),
    
    # filtering and sort 
    path('sort/by/club/<str:club_name>', views.SortByClub.as_view(), name='sort_by_club'),
    path('sort/by/position/<str:position>', views.SortByPositon.as_view(), name='sort_by_position'),
    path("filter-form/", views.PlayerFilterFormView.as_view(), name='player_filter_form'),
    path('sort_by_club_and_positon/', views.sort_by_club_and_positon, name='sort_by_club_and_positon')
    
]

django-projects/db_managment/players/models.py
from datetime import date
from django.db import models

# pip install django_unicorn
# pip install django-debug-toolbar

# Create your models here.
class Club(models.Model):
    name = models.CharField(max_length=150)
    logo = models.ImageField(upload_to='club_logos/%Y/%m/%d')

    def __str__(self):
        return str(self.name)


def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))
 

class Player(models.Model):
    
    POSITONS = (
        ('gk', "Goalkeeper"),
        ('df', "Deffender"),
        ('md', "Middle Deffender"),
        ('fw', "Forward"),
        ('st', "Striker"),
    )

    
    name = models.CharField(max_length=150)
    birthday = models.DateField(blank=True)
    age = models.PositiveIntegerField(default=0, blank=True)
    image = models.ImageField(upload_to='players/%Y/%m/%d')    
    height = models.FloatField(blank=True)
    weight = models.FloatField(blank=True)
    country = models.CharField(max_length=150,blank=True)
    club = models.ForeignKey(Club, on_delete=models.PROTECT, related_name='players', null=True)
    position = models.CharField(choices=POSITONS,blank=True, max_length=50)
    current_price = models.FloatField(default=0,blank=True)
    
    def __str__(self):
        return str(self.name)
    
        
    def get_country(self):
        return self.country.capitalize()
    # def save(self):
    #     self.age = calculate_age(self.birthday)
    #     self.save()


class PlayerImages(models.Model):
    image = models.ImageField(upload_to='players/%Y/%m/%d')
    player = models.ForeignKey(
        Player,
        default=None,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='player_images')
    
    def __str__(self):
        return self.player.name

    class Meta:
        verbose_name = 'Player rasmlari'
        verbose_name_plural = 'Player rasmlari'

django-projects/db_managment/players/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.urls import reverse

from django.shortcuts import render, redirect
from django.views.generic import View, ListView,DetailView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Player,Club

from django.db.models import Min, Max, Avg , Q, F

from django.core.mail import send_mail, send_mass_mail
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

class PlayerListView(ListView):
    model = Player
    template_name = "players/players.html"
    context_object_name = "object_list"
    
    def get_queryset(self):
        # return Player.objects.filter(current_price__gte=100000000)
        return Player.objects.filter(height__range=[160, 180])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["club_list"] = Club.objects.all()
        context["info"] = "Players list"
        return context
    





class PlayersHomeView(LoginRequiredMixin,ListView,FormView):
    model = Player
    template_name = "players/players.html"
    form_class = UserCreationForm
    success_url = '/'
    # context_object_name = "object_list"
    
    def get_queryset(self):
        mun = Club.objects.get(name='Manchester United')
        qs = super().get_queryset()
        
        return qs.filter(club=mun.id)
    

        return total
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["club_list"] = Club.objects.all()
        return context
    
    



    
    # http get method handler 
    # def get(self,request):
        
        
        
    #     players = Player.objects.all()
    #     # for p in players:
    #     #     p.age = calculate_age(p.birthday)
    #     #     p.save()
    #     clubs = Club.objects.all()       

    #     data = {
    #         "object_list":players,
    #         "club_list":clubs,
    #     }
    #     return render(request, "players/players.html", context=data)
    
    # # http post method handler 
    # def post(self,request):
    #     pass

class PlayerDetailView(DetailView):
    model = Player
    template_name = "players/player_detail.html"

class SortByClub(View):
    
    def get(self,request,club_name):
        print(club_name)
        club = Club.objects.get(name=club_name)
        players = Player.objects.filter(club=club)
        
        clubs = Club.objects.all()
        data = {
            "object_list":players,
             "club_list":clubs,
             "info":f"Sorting players by club : {club_name}"
        }
        return render(request, "players/players.html", context=data)
        
    
class SortByPositon(View):
    
    def get(self,request,position):

        players = Player.objects.filter(position=position)
        
        clubs = Club.objects.all()
        data = {
            "object_list":players,
             "club_list":clubs,
             "info":f"Sorting players by postion."
        }
        return render(request, "players/players.html", context=data)

class PlayerFilterFormView(View):
    
    
    def get(self,request):
        price = request.GET.get("price")
        age = request.GET.get("age")

        
        if price or age:
            object_list = Player.objects.filter(
                Q(current_price__lte=int(price)) | Q(age__lte=int(age)))
            print(object_list)
            data = {
                "object_list":object_list,
                "info":f"Sorting players by filter form."
            }
            return render(request, "players/players.html", context=data)
        else:
            return render(request, "players/players.html")
        


def sort_by_club_and_positon(request):

    club = Club.objects.get(name=request.POST.get("country"))
    players = Player.objects.filter(
        Q(club=club.id) &  Q(position=request.POST.get("positon"))
    )
    clubs = Club.objects.all() 
    data = {
        "object_list":players,
        "club_list":clubs,
    }
    return render(request, "players/players.html", context=data)

django-projects/db_managment/templates/players/player_detail.html
{% extends '../base.html' %}
{% load static %}

{% block content %}

    <script>
        if ( window.history.replaceState ) {
            window.history.replaceState( null, null, window.location.href );
        }
    </script>

    <main>
        <br>
        <br>
        <div class="container">
            {% if messages %}
            {% for message in messages %}
                <div class="messages">
                    <h4>{{message}}</h4>
                    <button onclick="this.parentElement.style.display= 'none'">X</button>
                </div>
            {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-12">
       
                    <div class="card shadow-lg px-5 py-2">
                        <div class="d-flex flex-wrap justify-content-between ">
                            <img width="150" height="150" src="{{object.image.url}}" alt="">
                            <div class="info">
                                <h4>{{object.name}}</h4>
                                <p>Club : <a href="" class="text-decoration-none">{{object.club}}</a> </p>
                                <p>{{object.country}}</p>
                                <p>{{object.age}}</p>
                                <p>{{object.height}}</p>
                                <p>{{object.weight}}</p>
                            </div>
                        </div>
                      </div>
                  
                </div>
            </div>
    

        </div>
    </main>

{% endblock %}

django-projects/db_managment/templates/players/players.html
{% extends 'base.html' %} {% load static %} {% block content %}

<script>
  if (window.history.replaceState) {
    window.history.replaceState(null, null, window.location.href);
  }
</script>

<main>
  <br />
  <br />
  <div class="container">
    {% if messages %} {% for message in messages %}
    <div class="messages">
      <h4>{{message}}</h4>
      <button onclick="this.parentElement.style.display= 'none'">X</button>
    </div>
    {% endfor %} {% endif %}
    <div class="row">
      <div class="col-3">
        <form action="{% url 'players:sort_by_club_and_positon' %}" method="post">
          {% csrf_token %}
          <select name="country" id="" class="form-select">
            {% for c in club_list %}
            <option value="{{c.name}}">{{c.name}}</option>
            {% endfor %}
          </select>
          <p>
            <input type="radio" name="positon"  value="gk" />
            <label for="pos">GK</label>
          </p>
          <p>
            <input type="radio" name="positon" value="df" />
            <label for="pos">DF</label>
          </p>
          <p>
            <input type="radio" name="positon"  value="md"/>
            <label for="pos">MD</label>
          </p>
          <p>
            <input type="radio" name="positon" value="fw"/>
            <label for="pos">FW</label>
          </p>
          <p>
            <input type="submit" value="Filter" class="btn btn-success">
          </p>
        </form>

        <div class="list-group">
          <a
            href="#"
            class="list-group-item list-group-item-action active"
            aria-current="true"
          >
            Categories
          </a>
          <a
            href="{% url 'players:sort_by_position' 'gk' %}"
            class="list-group-item list-group-item-action"
          >
            Goalkeeper
          </a>
          <a
            href="{% url 'players:sort_by_position' 'df' %}"
            class="list-group-item list-group-item-action"
          >
            Deffender
          </a>
          <a
            href="{% url 'players:sort_by_position' 'md' %}"
            class="list-group-item list-group-item-action"
          >
            Middle Deffender
          </a>
          <a
            href="{% url 'players:sort_by_position' 'fw' %}"
            class="list-group-item list-group-item-action"
          >
            Forward
          </a>
          <a
            href="{% url 'players:sort_by_position' 'st' %}"
            class="list-group-item list-group-item-action"
          >
            Stiker
          </a>
        </div>
        <div class="list-group mt-3">
          <a
            href="#"
            class="list-group-item list-group-item-action active"
            aria-current="true"
          >
            Sort by Club
          </a>
          {% for c in club_list %}
          <a
            href="{% url 'players:sort_by_club' c.name %}"
            class="list-group-item list-group-item-action"
          >
            <img width="30" height="30" src="{{c.logo.url}}" alt="" />
            {{c.name}}
          </a>
          {% endfor %}
        </div>

        <form
          action="{% url 'players:player_filter_form' %}"
          method="get"
          class="mb-5"
        >
          <label for="disabledRange" class="form-label"
            >Filter by price :
            <span class="slected_price"></span>
          </label>
          <input
            name="price"
            type="text"
            id="price"
            value="0"
            class="form-control"
          />
          <label for="disabledRange" class="form-label"
            >Filter by age :
            <span class="slected_age"></span>
          </label>
          <input
            type="range"
            name="age"
            value="0"
            id="age"
            min="0"
            max="60"
            class="form-range"
            id="disabledRange"
          />

          <div class="my-2">
            <button type="submit" class="btn btn-outline-success">
              Filter
            </button>
          </div>
        </form>
      </div>
      <div class="col-9">
        {% if info %}
        <h3>{{info}}</h3>
        {% else %}
        <h3>Players : {{info}}</h3>
        {% endif %} {% for obj in object_list %}
        <div class="card shadow-lg px-5 py-2 my-2">
          <div class="d-flex flex-wrap justify-content-between">
            <img width="150" height="150" src="{{obj.image.url}}" alt="" />
            <div class="info">
              <h4>{{obj.name}}</h4>
          
              <p>
                Club : <a href="" class="text-decoration-none">{{obj.club}}</a>
              </p>
              <div class="d-flex flex-wrap justify-content-between" style="gap: 10px;">
              <p><b>Country </b> : {{obj.get_country}}</p>
              <p><b>Price </b> :  {{obj.current_price}}</p>
              <p><b>Age </b> : {{obj.age}}</p>
              <p><b>Height </b> : {{obj.height}}</p>
              <p><b>Weight </b> : {{obj.weight}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

  </div>
</main>

{% endblock %}